#ifndef _ERRORS_H_
#define _ERRORS_H_

#define ERROR_WRITING_PIPE 1
#define ERROR_CREATING_SHMEM 2
#define ERROR_FTRUNCATE_SHMEM 3
#define ERROR_MMAP_SHMEM 4
#define ERROR_MUNMAP_SHMEM 5
#define ERROR_CLOSING_SHMEM 6
#define ERROR_UNLINKING_SHMEM 7
#define ERROR_READING_SHMEM 8
#define ERROR_OPENING_SEM 9
#define ERROR_CLOSING_SEM 10
#define ERROR_UNLINKING_SEM 11
#define ERROR_NO_FILES 12
#define ERROR_CREATING_SEM 13
#define ERROR_CREATING_FILE 14
#define ERROR_CLOSING_FILE 15
#define ERROR_SELECT 16
#define ERROR_READING_SLAVE_PIPE 17
#define ERROR_CREATING_PIPE 18
#define ERROR_CLOSING_PIPE 19
#define ERROR_DUPLICATING_PIPE 20
#define ERROR_CREATING_SLAVE 21

#endif